### ISSUE TITLE
Unformatted text on PyPI

### ISSUE THREAD

**Issue by mgedmin** [kennethreitz/tablib#174]
The current release on PyPI has a long_description with a ReStructuredText error that causes it to be shown unformatted:
![ekrano nuotrauka is 2014-10-30 15 17 48](https://cloud.githubusercontent.com/assets/159967/4843921/2ed5f88a-6037-11e4-8fa3-90346fab0051.png)

The (hidden) error is
> <string>:157: (ERROR/3) Document or section may not begin with a transition.

and it's in this bit:

![ekrano nuotrauka is 2014-10-30 15 18 34](https://cloud.githubusercontent.com/assets/159967/4843930/49c2b052-6037-11e4-8c1e-49f0eee894f4.png)

It would be nice if somebody with PyPI access (i.e. @kennethreitz) fixed the RST error in the long_description field of the current release.

BTW README.rst in master doesn't have this problem, so making a new release would fix this too.

**Comment by kennethreitz** [comment]
Fixed!

**Comment by mgedmin** [comment]
Thank you!
