### ISSUE TITLE
importing csv data with "foo, bar"

### ISSUE THREAD

**Issue by pcompassion** [kennethreitz/tablib#188]
quoting to escape `,` works fine for the first column but not for the second column..

`"foo, bar", hello` is read as `foo, bar`, `hello`

`hello, "foo, bar"` is read as `hello`, `"foo`, `bar"`

**Comment by tsroten** [comment]
It seems this is more of a limitation with Python's `csv` module. For example:
```python
import csv
from io import StringIO

reader = csv.reader(StringIO('hello, "foo, bar"'))
next(reader)  # returns ['hello', ' "foo', ' bar"']

reader = csv.reader(StringIO('hello,"foo,bar"'))
next(reader)  # returns ['hello', 'foo,bar']
```
