### ISSUE TITLE
Writing a .xlsx file throws "NameError: name 'frzn_col_idx' is not defined"

### ISSUE THREAD

**Issue by FredrikHedman** [kennethreitz/tablib#218]
Using Python 3.5.0 I get a NameError when executing the code below.  Reading the code and grep-finding in the tablib package does not find the name frzn_col_idx anywhere.  Seems to be a bug. 

`import tablib

data = tablib.Dataset()
headers = ('first_name', 'last_name')
data = [
    ('John', 'Adams'),
    ('George', 'Washington')
]
data = tablib.Dataset(*data, headers=headers)
book = tablib.Databook((data, data, data))

# Works fine
with open('data.xls', 'wb') as f: f.write(book.xls)

# Throws a NameError
with open('data.xlsx', 'wb') as f: f.write(book.xlsx)
`

This generates:

`---> 18    f.write(book.xlsx)

 ... /python3.5/site-packages/tablib/formats/_xlsx.py in export_book(databook, freeze_panes)
     57         ws.title = dset.title if dset.title else 'Sheet%s' % (i)
     58 
---> 59         dset_sheet(dset, ws, freeze_panes=freeze_panes)
     60 
     61 

  ... /python3.5/site-packages/tablib/formats/_xlsx.py in dset_sheet(dataset, ws, freeze_panes)
    126                 if freeze_panes:
    127                     # We want to freeze the column after the last column
--> 128                     ws.freeze_panes = '%s%s' % (frzn_col_idx, row_number)
    129 
    130             # bold separators

NameError: name 'frzn_col_idx' is not defined
`

**Comment by iurisilvio** [comment]
It is fixed in 5ba6f5d91a151a4376521c93afdf2cefdb213e0c, deserve a new release to fix XLSX format. @kennethreitz

**Comment by kennethreitz** [comment]
Released! https://pypi.python.org/pypi/tablib/0.11.2
