### ISSUE TITLE
Databook.add_sheet should accept a sheet name as an argument

### ISSUE THREAD

**Issue by franciscod** [kennethreitz/tablib#222]
Is there any way to do it that I could've missed? Thanks!

**Comment by franciscod** [comment]
https://github.com/kennethreitz/tablib/blob/master/tablib/formats/_xlsx.py#L57

hmmmm

**Comment by kennethreitz** [comment]
Currently unsupported :)

**Comment by franciscod** [comment]
https://github.com/kennethreitz/tablib/blob/master/tablib/core.py#L170

hmm!

**Comment by kennethreitz** [comment]
ah, i take that back! it's been a while since I wrote that code :)

**Comment by franciscod** [comment]
this works!

```
book = tablib.Databook()
data = tablib.Sheet('THE AWESOME SHEET TITLE YOU WANT TO GET)
book.add_sheet(data)
```
