### ISSUE TITLE
Looks like release v0.11.3 is not uploaded on PyPi 

### ISSUE THREAD

**Issue by chhantyal** [kennethreitz/tablib#258]
Hi everyone. 
I was looking into this commit https://github.com/kennethreitz/tablib/pull/145 which supports custom delimiter in CSV files. It looks to be released in this tag https://github.com/kennethreitz/tablib/releases/tag/v0.11.3

But latest release on PyPi is 0.11.2. See here https://pypi.org/project/tablib/

Was it intentional or just forgotten to hit upload command?

**Comment by kennethreitz** [comment]
let's ask the maintainer :)
@iurisilvio?

**Comment by iurisilvio** [comment]
@kennethreitz I don't have PyPI permission. :) Can you give me this permission?

**Comment by chhantyal** [comment]
Hi all,

Any updates on this one? Thanks.

**Comment by iurisilvio** [comment]
Yes! I published it now.

https://pypi.python.org/pypi/tablib

Let me know if you have any other issues with this release.
