### ISSUE TITLE
Bump version required v0.11.4

### ISSUE THREAD

**Issue by andriisoldatenko** [kennethreitz/tablib#264]
I think we should bump version.
last release was `v0.11.3` on Feb 16 ( less than 1 year ago)
thanks

**Comment by saily** [comment]
@kennethreitz could you please release new full python3.6 compat version (see: #263)?

**Comment by luizfb** [comment]
I just opened Issue #267 cause pip version is broken on 3.6, even though installing straight from master works fine. This should be republished to pip.

In the meantime, the following will do:
```
pip install git+https://github.com/kennethreitz/tablib.git
```

**Comment by iurisilvio** [comment]
Done. v0.11.4 released.

**Comment by kennethreitz** [comment]
\o/
