### ISSUE TITLE
Talos Security Advisory for Tablib

### ISSUE THREAD

**Issue by regiwils** [kennethreitz/tablib#289]
Security vulnerability found and reported notice on 4/18 and 5/9/17 via email. Please provide email and PGP to receive encrypted report.

**Comment by kennethreitz** [comment]
Can you provide it unencrypted? I do not have PGP setup.

**Comment by kennethreitz** [comment]
One of my collaborators, @lukasa might be able to receive the PGP communication on my behalf. Up for it, Corey?

**Comment by Lukasa** [comment]
I can do that. Email address is on my GitHub profile, PGP key can be found either by examining my signed GitHub commits or on [Keybase](https://keybase.io/lukasa).

**Comment by regiwils** [comment]
Hello Cory,

The attached file encrypted with your keybase PGP.

**Comment by Lukasa** [comment]
No file is present.

**Comment by regiwils** [comment]
Hello,

Here’s the screenshot of the email including the file.  Unsure if it was stripped on your end.  I’ve attached unencrypted report.

**Comment by Lukasa** [comment]
You aren't emailing me, you're emailing Github.

**Comment by regiwils** [comment]
Email forwarded directly to your email address.

**Comment by Lukasa** [comment]
Which email address did you forward to? I've received no email.

**Comment by regiwils** [comment]
The message was blocked on your end.  Please email me from your email address (which I can reply to)  versus Github and this should solve the issue.

Thank you,

Regina Wilson
Engineer. Research
regiwils@cisco.com<mailto:regiwils@cisco.com>




[cid:CFA14CB5-B7B2-4FF7-8313-22D495F607D5@vrt.sourcefire.com]

On Jun 13, 2017, at 9:42 AM, Cory Benfield <notifications@github.com<mailto:notifications@github.com>> wrote:


Which email address did you forward to? I've received no email.

**Comment by kennethreitz** [comment]
v0.11.5 released, which fixes this!

**Comment by regiwils** [comment]
Thanks for the update!


Regina Wilson
Engineer. Research
regiwils@cisco.com<mailto:regiwils@cisco.com>




[cid:CFA14CB5-B7B2-4FF7-8313-22D495F607D5@vrt.sourcefire.com]

On Jun 13, 2017, at 12:32 PM, Kenneth Reitz <notifications@github.com<mailto:notifications@github.com>> wrote:


v0.11.5 released, which fixes this!

**Comment by kennethreitz** [comment]
@regiwils thanks for the report!
