### ISSUE TITLE
Inserting image

### ISSUE THREAD

**Issue by Smosker** [kennethreitz/tablib#295]
Hello! Is where a way to insert an image in xlsx file using this module?
Trying to do this:
```
book = tablib.Databook()

response = requests.get(file.file.url, stream=True, timeout=5)
sheet = tablib.Dataset()
sheet.headers = ('name', 'file')
sheet.append((file.name, response.content))
book.add_sheet(sheet)

response = HttpResponse(book.export('xlsx'),
                                    content_type='application/vnd.openxmlformats-officedocument.spreadsheetml.sheet')
```

But instead of image i just get field in excel file which look like:
`b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x.....'`

Or maybe i can create sheet with `xlsxwirter/openpyxl` and then somehow insert to tablib `Databook`?

**Comment by kennethreitz** [comment]
there is not
