### ISSUE TITLE
JSON export broken when using `ujson`

### ISSUE THREAD

**Issue by TheKevJames** [kennethreitz/tablib#297]
When `ujson` is installed, [export_set](https://github.com/kennethreitz/tablib/blob/46102d4be718ee6fd6c003c1387df7c940e65b2c/tablib/formats/_json.py#L28) and [export_book](https://github.com/kennethreitz/tablib/blob/46102d4be718ee6fd6c003c1387df7c940e65b2c/tablib/formats/_json.py#L33) fail with

    # ...
    File "/usr/local/lib/python3.6/site-packages/tablib/formats/_json.py", line 30, in export_set
        return json.dumps(dataset.dict, default=date_handler)
    TypeError: 'default' is an invalid keyword argument for this function

This is because `ujson.dumps` [does not support the `default` kwarg and does not plan to in the future](https://github.com/esnme/ultrajson/issues/215).

**Comment by omidraha** [comment]
I have the same issue.

**Comment by TheKevJames** [comment]
If you need/want to keep the `ujson` module installed, as I do, you can also monkeypatch `tablib`:

    import json
    import tablib

    tablib.formats.json.json = json
