### ISSUE TITLE
import/export from pandas dataframes

### ISSUE THREAD

**Issue by kennethreitz** [kennethreitz/tablib#300]
This feature would be awesome.

**Comment by kennethreitz** [comment]
@jasonamyers may take a stab at this

**Comment by jasonamyers** [comment]
Hey @kennethreitz pandas is 2.7 or higher now. So the 2.6 tests fail ATM.

**Comment by kennethreitz** [comment]
✨🍰✨

**Comment by kennethreitz** [comment]
just going to drop 2.6 support instead

**Comment by audiolion** [comment]
Can probably close this one off now!
