### ISSUE TITLE
Pandas support

### ISSUE THREAD

**Issue by audiolion** [kennethreitz/tablib#306]
Can we make a tablib[pandas] optional install? with 0.12.0 there is now a pandas dependency that is a huge dependency to add for everyone by default.

**Comment by kennethreitz** [comment]
what makes it a huge dependency? they ship wheels.

**Comment by audiolion** [comment]
Wrong term, sorry, but pandas ships with a wheel and it relies on numpy, so for me at least it adds two minutes of time to build the wheels which makes CI tests slower whenever the cache gets busted.

**Comment by signalkraft** [comment]
For us the wheels don't get used, maybe because we are running in docker with alpine. Our build times increased by several minutes because of numpy and pandas:

```
Collecting pandas (from tablib->django-import-export==0.5.1->-r requirements.txt (line 10))
  Downloading pandas-0.20.3.tar.gz (10.4MB)
...
  Downloading numpy-1.13.1.zip (5.0MB)
...
```

Making it optional would be very helpful in our case.

**Comment by kennethreitz** [comment]
I'll accept a pr which makes it optional.

**Comment by signalkraft** [comment]
@audiolion let me know if you need me to make the PR
