### ISSUE TITLE
HISTORY.rst is missing information for 0.12.0 and 0.12.1 releases

### ISSUE THREAD

**Issue by peterfarrell** [kennethreitz/tablib#308]
Noticed that the HISTORY.rst file is missing info for the 0.12.0 and 0.12.1 releases. I'd do a PR but I have no context on what has changed in these releases.

**Comment by kennethreitz** [comment]
this library isn't very well maintained (by me)

**Comment by philfreo** [comment]
+1 would especially love to know if there are any backwards incompatible changes

**Comment by tomscytale** [comment]
@kennethreitz - Is the code for the 0.12.0 and 0.12.1 releases in github? If there is more information maybe someone could step up and help.
