### ISSUE TITLE
there was wrong with tablib export to xlsx, is it a new bug??

### ISSUE THREAD

**Issue by geosson** [kennethreitz/tablib#323]
# ws.cell bug
   ###formats/_xlsx.py at line 122: 
  ---
cell = ws.cell('%s%s' % (col_idx, row_number))
TypeError: cell() missing 1 required positional argument: 'column'
---
---

  I have review the source code and change here from

    cell = ws.cell('%s%s' % (col_idx, row_number))

        to

    cell = ws['%s%s' % (col_idx, row_number)]
   ---

**Comment by imomaliev** [comment]
for anyone having this issue https://github.com/jieter/django-tables2/issues/641#issuecomment-450636458

> Yes, this is an upstream issue in tablib. Until that's fixed, using `tablib==0.11.4` should work.
