### ISSUE TITLE
PyPI release

### ISSUE THREAD

**Issue by axnsan12** [kennethreitz/tablib#354]
The last version on PyPI is 0.12.1 from September 1st, 2017. 

There were a lot of changes to the code since then, including, crucially, https://github.com/kennethreitz/tablib/pull/296 which fixes a long-standing bug that has been preventing tablib from working properly for more than a year (openpyxl 2.5.0, which turned the warning into a breaking change, was released on January 24th, 2018).

I see that a few people have been bringing new life to this project, please consider pushing a new release to PyPI as part of this!

**Comment by ParthS007** [comment]
Thanks, @axnsan12 for opening the Issue, I will ping @kenneth-reitz @timofurrer for the same and will release the latest version asap.

**Comment by timofurrer** [comment]
I've just released **v0.13.0** 🎉
