### ISSUE TITLE
New import/export interface for 1.0

### ISSUE THREAD

**Issue by kenneth-reitz** [kennethreitz/tablib#46]
- `data.export('json')` instead of `data.json`.
- `data.import('json', value)` instead of `data.json = value`.

**Comment by iurisilvio** [comment]
The #191 PR was merged and I think this is done. Also, 

Maybe it deserve better docs.

```
dataset.export('xlsx', freeze_panes=False)
dataset.load('a,b,c\nv1,v2,v3\n', format='csv')
```
